/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package network;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 *
 * @author mmwoodfo
 */
public class mainView extends javax.swing.JFrame {

    public LinkedList list = new LinkedList();
    public String universalNewLineChar = System.getProperty("line.separator");

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();

        //hides dependencies options if linked list is empty
        /*if(list.isEmpty() == true){
            //remove nodeDependenciesTxt and nodeDependencieslbl
            nodeDependenciesTxt.setVisible(false);
            nodeDependencieslbl.setVisible(false);
        //shows dependencies options if linked list is not empty
        }else{
            nodeDependenciesTxt.setVisible(true);
            nodeDependencieslbl.setVisible(true);
        }*/
        durationErrorLbl.setVisible(false); //hides error label on start up
        errorLbl.setVisible(false); //hides error label on start up
        requiredLbl.setVisible(false);
        infoTxt.setVisible(false);
        repoRequired.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeNamelbl = new javax.swing.JLabel();
        nodeDurationlbl = new javax.swing.JLabel();
        nodeDependencieslbl = new javax.swing.JLabel();
        nodeNameTxt = new javax.swing.JTextField();
        nodeDurationTxt = new javax.swing.JTextField();
        addNodeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayNodesField = new javax.swing.JTextArea();
        nodeDependenciesTxt = new javax.swing.JTextField();
        listIndividualNodes = new javax.swing.JButton();
        durationErrorLbl = new javax.swing.JLabel();
        errorLbl = new javax.swing.JLabel();
        listPathsBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        requiredLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTxt = new javax.swing.JTextArea();
        report = new javax.swing.JButton();
        changeDuration = new javax.swing.JButton();
        reportTitle = new javax.swing.JLabel();
        reportTitleTxt = new javax.swing.JTextField();
        repoRequired = new javax.swing.JLabel();
        criticalPathBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        nodeNamelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeNamelbl.setText("Name: ");

        nodeDurationlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeDurationlbl.setText("Duration:");

        nodeDependencieslbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeDependencieslbl.setText("Dependencies:");

        nodeNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeNameTxt.setToolTipText("Enter your activities name");

        nodeDurationTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeDurationTxt.setToolTipText("Enter your activities duration as a number");

        addNodeBtn.setBackground(new java.awt.Color(0, 0, 0));
        addNodeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addNodeBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNodeBtn.setText("Add +");
        addNodeBtn.setToolTipText("Adds activity to your list");
        addNodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNodeBtnActionPerformed(evt);
            }
        });

        displayNodesField.setColumns(20);
        displayNodesField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        displayNodesField.setRows(5);
        jScrollPane1.setViewportView(displayNodesField);

        nodeDependenciesTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nodeDependenciesTxt.setToolTipText("Enter your dependicies seperated by a comma");

        listIndividualNodes.setBackground(new java.awt.Color(0, 0, 0));
        listIndividualNodes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listIndividualNodes.setForeground(new java.awt.Color(255, 255, 255));
        listIndividualNodes.setText("List Individual Nodes");
        listIndividualNodes.setToolTipText("This will sort your individual nodes by their duration");
        listIndividualNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIndividualNodesActionPerformed(evt);
            }
        });

        durationErrorLbl.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        durationErrorLbl.setForeground(new java.awt.Color(255, 0, 0));
        durationErrorLbl.setText("Not a number!");

        errorLbl.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLbl.setText("Error: Could not Add Node");

        listPathsBtn.setBackground(new java.awt.Color(0, 0, 0));
        listPathsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listPathsBtn.setForeground(new java.awt.Color(255, 255, 255));
        listPathsBtn.setText("List Paths");
        listPathsBtn.setToolTipText("This will list the paths sorted from shortest to longest");
        listPathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPathsBtnActionPerformed(evt);
            }
        });

        helpBtn.setBackground(new java.awt.Color(0, 51, 0));
        helpBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        helpBtn.setForeground(new java.awt.Color(255, 255, 255));
        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        aboutBtn.setBackground(new java.awt.Color(0, 51, 0));
        aboutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(102, 0, 0));
        Reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset All Nodes");
        Reset.setToolTipText("Delete all activities");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        requiredLbl.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        requiredLbl.setForeground(new java.awt.Color(255, 0, 51));
        requiredLbl.setText("*Required");

        infoTxt.setBackground(new java.awt.Color(204, 204, 204));
        infoTxt.setColumns(20);
        infoTxt.setRows(5);
        jScrollPane2.setViewportView(infoTxt);

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Export to File");
        report.setToolTipText("");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        changeDuration.setBackground(new java.awt.Color(0, 0, 0));
        changeDuration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changeDuration.setForeground(new java.awt.Color(255, 255, 255));
        changeDuration.setText("Change Duration");
        changeDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDurationActionPerformed(evt);
            }
        });

        reportTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reportTitle.setText("Report Title:");

        reportTitleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTitleTxtActionPerformed(evt);
            }
        });

        repoRequired.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        repoRequired.setForeground(new java.awt.Color(255, 0, 0));
        repoRequired.setText("*Required");
        repoRequired.setToolTipText("");

        criticalPathBtn.setBackground(new java.awt.Color(0, 0, 0));
        criticalPathBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        criticalPathBtn.setForeground(new java.awt.Color(255, 255, 255));
        criticalPathBtn.setLabel("Critical Path");
        criticalPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criticalPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nodeNamelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nodeDurationlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nodeDependencieslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNodeBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nodeNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(nodeDurationTxt)
                                    .addComponent(nodeDependenciesTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationErrorLbl)
                                    .addComponent(requiredLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(changeDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aboutBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reportTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reportTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(repoRequired)))))))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listIndividualNodes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPathsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(criticalPathBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeNamelbl)
                    .addComponent(nodeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requiredLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeDurationlbl)
                    .addComponent(nodeDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationErrorLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeDependencieslbl)
                    .addComponent(nodeDependenciesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNodeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeDuration)
                .addGap(30, 30, 30)
                .addComponent(errorLbl)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportTitle)
                    .addComponent(reportTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repoRequired))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(report)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutBtn)
                    .addComponent(helpBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reset)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(listIndividualNodes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPathsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criticalPathBtn)
                .addGap(32, 32, 32))
        );

        reportTitle.getAccessibleContext().setAccessibleName("Report title:");
        repoRequired.getAccessibleContext().setAccessibleName("repoRequired");
        criticalPathBtn.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

//=========================== Add Node Button ========================================
    private void addNodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNodeBtnActionPerformed

        boolean isNum = false;
        Node newNode = new Node();
        errorLbl.setVisible(false);
        Boolean nameEmpty = false;
        //sets name of node
        String nodeNameStr = nodeNameTxt.getText();
        if (nodeNameStr.equals("")) {
            nameEmpty = true;
            requiredLbl.setVisible(true);
        } else {
            newNode.setName(nodeNameStr);
            requiredLbl.setVisible(false);
        }

        //try-catch to check if input is an int
        try {
            //input is an integer - convert to int
            int nodeDurationInt = Integer.parseInt(nodeDurationTxt.getText());
            //sets duration of node
            newNode.setDuration(nodeDurationInt);
            durationErrorLbl.setVisible(false);
            isNum = true;
        } catch (NumberFormatException e) {
            //input is not an integer
            durationErrorLbl.setVisible(true);
            isNum = false;
        }

        if (isNum == true && nameEmpty == false) {
            //convert CSV to array
            String nodeDependiciesStr = nodeDependenciesTxt.getText();
            String[] nodeDependiciesArr = nodeDependiciesStr.split("\\s*,\\s*");
            //sets node dependicies array
            newNode.setDependicies(nodeDependiciesArr);
            newNode.setDependiciesCpy2(nodeDependiciesArr);
            newNode.setDependiciesCpy2(nodeDependiciesArr);

            //add node to end of linked list
            list.addLast(newNode);

            //displays the contents of the linked list
            displayNodesField.setText(list.printString());

            //shows dependencies options after first node is added
            //nodeDependenciesTxt.setVisible(true);
            //nodeDependencieslbl.setVisible(true);
            //resets textFields
            nodeNameTxt.setText("");
            nodeDurationTxt.setText("");
            nodeDependenciesTxt.setText("");
        }//end if isNum == true
        else { //error, could not add node
            errorLbl.setText("Error: Could not Add Node");
            errorLbl.setVisible(true);
        }
    }//GEN-LAST:event_addNodeBtnActionPerformed

//================ called by listPtahsBtnActionPreformed ==========================
    private String listPathsFunction() {
        //--------- Error Checking ----------------
        Node[] end2 = list.findLastNodes();
        Node[] end1 = list.findLastNodes();
        Node[] start1 = list.findFirstNodes();
        if (list.isEmpty() == true) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in the list");
            displayNodesField.setText("");
            list.resetList();
        } else if (start1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no starting nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no ending nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end2[1] != null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There is more than one ending node");
            displayNodesField.setText("");
            list.resetList();

            //---------- Error checking passed ------------------
        } else {
            errorLbl.setVisible(false);
            boolean error = false;
            int numOfPaths = list.numberOfPaths();

            pathObject[] pathObj = new pathObject[numOfPaths];
            //------------- populating path object array ---------------
            for (int i = 0; i < numOfPaths; i++) {
                pathObj[i] = list.getPathObj();

                //---- if there is an unconnected node -----
                if (pathObj[i] == null) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There are unconnected nodes");
                    displayNodesField.setText("");
                    list.resetList();
                    error = true;
                    break;
                }
                //------ if there is a cycle ------
                if (list.cycleCheck(pathObj[i]) == true) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There is a cycle");
                    displayNodesField.setText("");
                    error = true;
                    list.resetList();
                    break;
                }
            }

            if (error == false) {
                pathObj = list.removeDuplicates(pathObj);

                //sort by duration
                pathObj = list.sortPaths(pathObj);

                String paths = "";

                for (int j = 0; j < pathObj.length; j++) {
                    paths += pathObj[j];
                }
                list.resetDependicies();
                return paths;
            }
        }
        return "";
    }

    //================ version of listPathsFunction called by FileWrite Function ==========================
    //======= only difference between normal one and this is that this one inserts an extra newline character between each path listing =======
    //======= In practice, this is really bad, but for our purposes, we can afford the extra code space (this is last deliverable) =======
    private String listReportPathsFunction() {
        //--------- Error Checking ----------------
        Node[] end2 = list.findLastNodes();
        Node[] end1 = list.findLastNodes();
        Node[] start1 = list.findFirstNodes();
        if (list.isEmpty() == true) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in the list");
            displayNodesField.setText("");
            list.resetList();
        } else if (start1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no starting nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no ending nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end2[1] != null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There is more than one ending node");
            displayNodesField.setText("");
            list.resetList();

            //---------- Error checking passed ------------------
        } else {
            errorLbl.setVisible(false);
            boolean error = false;
            int numOfPaths = list.numberOfPaths();

            pathObject[] pathObj = new pathObject[numOfPaths];
            //------------- populating path object array ---------------
            for (int i = 0; i < numOfPaths; i++) {
                pathObj[i] = list.getPathObj();

                //---- if there is an unconnected node -----
                if (pathObj[i] == null) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There are unconnected nodes");
                    displayNodesField.setText("");
                    list.resetList();
                    error = true;
                    break;
                }
                //------ if there is a cycle ------
                if (list.cycleCheck(pathObj[i]) == true) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There is a cycle");
                    displayNodesField.setText("");
                    error = true;
                    list.resetList();
                    break;
                }
            }

            if (error == false) {
                pathObj = list.removeDuplicates(pathObj);

                //sort by duration
                pathObj = list.sortPaths(pathObj);

                String paths = "";

                for (int j = 0; j < pathObj.length; j++) {
                    paths += pathObj[j];
                    paths += universalNewLineChar;
                }
                list.resetDependicies();
                return paths;
            }
        }
        return "";
    }
    
    private void listPathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPathsBtnActionPerformed

        String pathsGiven = listPathsFunction();
        displayNodesField.setText(pathsGiven);
    }//GEN-LAST:event_listPathsBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
        infoTxt.setVisible(true);
        infoTxt.setLineWrap(true);
        infoTxt.setText("This program written and\n"
                + "designed by the following\n"
                + "students for CSE360, for the\n"
                + "Fall of 2018:\n"
                + "Meg Woodford\n"
                + "Matthew Bumb\n"
                + "Xinyi Lui\n"
                + "and Melissa Smeester\n"
                + "\n"
                + "To allow users to create a\n"
                + "network diagram, and find all\n"
                + "paths through its nodes,\n"
                + "sorted by duration.");
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed

        infoTxt.setVisible(true);
        infoTxt.setLineWrap(true);
        infoTxt.setText("Nodes should be formatted in the following manner:\n"
                + "    Name: string of characters and/or numbers\n"
                + "    Duration: a positive integer between 0 and 2,147,483,647\n"
                + "    Dependencies: Strings (case-sensitive), matching your node names,\n"
                + "    and separated by commas.\n"
                + "\n"
                + "-Press 'Add +' to add the node to the list.\n"
                + "-Press the 'List Individual Nodes' button to see all nodes added so far.\n"
                + "-Press the 'List Paths' button to see all paths through the network\n"
                + "diagram.\n"
                + "-Press 'Reset' to clear the list of all nodes.\n"
                + "-Press Export To File once you've entered a report file name in the box\n"
                + "\n"
                + "If you are having trouble adding a node, be sure\n"
                + "to make sure all text fields are filled in. If you are experiencing\n"
                + "a red error message, follow the directions and try to re-add the node.\n"
                + "For all other questions, please refer to the user manual. \n");
    }//GEN-LAST:event_helpBtnActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        errorLbl.setVisible(true);
        errorLbl.setText("Program Reset - All Activities Removed");
        displayNodesField.setText("");
        list.resetList();
        durationErrorLbl.setVisible(false);
        requiredLbl.setVisible(false);

        //resets textFields
        nodeNameTxt.setText("");
        nodeDurationTxt.setText("");
        nodeDependenciesTxt.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void listIndividualNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIndividualNodesActionPerformed

        //displays the contents of the linked list
        if (list.isEmpty() == false) {
            list.sortNodesABC();
            displayNodesField.setText(list.printString());
            errorLbl.setVisible(false);
        } else {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in list");
        }

    }//GEN-LAST:event_listIndividualNodesActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        boolean titleEmpty = false;
        
        
        if (list.isEmpty() == true) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in list");
        } else {
            try {
                String title = reportTitleTxt.getText();
                if (title.equals("")) {
                    titleEmpty = true;
                    repoRequired.setVisible(true);
                } else {
                    repoRequired.setVisible(false);
                }
                //date and time of creation
                DateFormat date = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                Date d = Calendar.getInstance().getTime();
                String repoDate = date.format(d);
                String createDate = repoDate;
                //change the store address of report for your computer
                FileWriter writer = new FileWriter(title + ".txt");
                BufferedWriter bw = new BufferedWriter(writer);
                //Write report title in text file
                bw.write("-TITLE:-");
                bw.write(universalNewLineChar);
                bw.write(title);
                bw.write(universalNewLineChar);
                bw.write(universalNewLineChar);
                //Write date and time in text file
                bw.write("-DATE:-");
                bw.write(universalNewLineChar);
                bw.write(createDate);
                bw.write(universalNewLineChar);
                bw.write(universalNewLineChar);
                //Sort nodes in ABC order, then List their activities and duration
                bw.write("-ACTIVITIES:-");
                bw.write(universalNewLineChar);
                list.sortNodesABC();
                bw.write(list.printActivitiesStringForReport());
                bw.write(universalNewLineChar);
                bw.write(universalNewLineChar);
                //List paths
                bw.write("-PATHS:-");
                bw.write(universalNewLineChar);
                bw.write(listReportPathsFunction());  //list path function call to print
                bw.write(universalNewLineChar);
                
                bw.close();
                reportTitleTxt.setText("");
                reportTitleTxt.requestFocus();
            } catch (Exception e) {
                errorLbl.setVisible(true); //error label to check if int
                errorLbl.setText("The input is not an integer!");
            }
            //displayNodesField.setText(list.report());
            errorLbl.setVisible(false);
        }
    }//GEN-LAST:event_reportActionPerformed

    private void changeDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDurationActionPerformed
        if (list.isEmpty() == true) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in the list");
        } else {
            //String name = "A"; 
            String name = nodeNameTxt.getText();

            //try-catch to check if input is an int
            try {
                //input is an integer - convert to int
                int newDuration = Integer.parseInt(nodeDurationTxt.getText());
                //changes node duration
                errorLbl.setVisible(false); //error label to check if int
                boolean tf = list.changeDuration(name, newDuration);
                //----- Check if node duration was changed -------
                if (tf == true) {
                    errorLbl.setVisible(false);
                    displayNodesField.setText(list.printString()); //show updated node
                } else {
                    errorLbl.setVisible(true);
                    errorLbl.setText("That node isn't in the list!");
                }//end else
                //----- Input is not integer ------
            } catch (NumberFormatException e) {
                //input is not an integer
                errorLbl.setVisible(true); //error label to check if int
                errorLbl.setText("The input is not an integer!");
            }
        }//end else
    }//GEN-LAST:event_changeDurationActionPerformed

    //can't delete this function...
    private void reportTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTitleTxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_reportTitleTxtActionPerformed

    private String criticalPathFunction() {
        //--------- Error Checking ----------------
        Node[] end2 = list.findLastNodes();
        Node[] end1 = list.findLastNodes();
        Node[] start1 = list.findFirstNodes();
        if (list.isEmpty() == true) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no nodes in the list");
            displayNodesField.setText("");
            list.resetList();
        } else if (start1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no starting nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end1[0] == null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There are no ending nodes");
            displayNodesField.setText("");
            list.resetList();
        } else if (end2[1] != null) {
            errorLbl.setVisible(true);
            errorLbl.setText("There is more than one ending node");
            displayNodesField.setText("");
            list.resetList();

            //---------- Error checking passed ------------------
        } else {
            errorLbl.setVisible(false);
            boolean error = false;
            int numOfPaths = list.numberOfPaths();

            pathObject[] pathObj = new pathObject[numOfPaths];
            //------------- populating path object array ---------------
            for (int i = 0; i < numOfPaths; i++) {
                pathObj[i] = list.getPathObj();

                //---- if there is an unconnected node -----
                if (pathObj[i] == null) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There are unconnected nodes");
                    displayNodesField.setText("");
                    list.resetList();
                    error = true;
                    break;
                }
                //------ if there is a cycle ------
                if (list.cycleCheck(pathObj[i]) == true) {
                    errorLbl.setVisible(true);
                    errorLbl.setText("There is a cycle");
                    displayNodesField.setText("");
                    error = true;
                    list.resetList();
                    break;
                }
            }

            if (error == false) {
                pathObj = list.removeDuplicates(pathObj);

                //sort by duration
                pathObj = list.sortPaths(pathObj);

                pathObj = list.criticalPath(pathObj);

                String paths = "";

                for (int j = 0; j < pathObj.length; j++) {
                    paths += pathObj[j];
                }
                list.resetDependicies();
                return paths;

            }
        }
        return "";
    }

    private void criticalPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criticalPathBtnActionPerformed
        String pathsGiven = criticalPathFunction();
        displayNodesField.setText(pathsGiven);
    }//GEN-LAST:event_criticalPathBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton addNodeBtn;
    private javax.swing.JButton changeDuration;
    private javax.swing.JButton criticalPathBtn;
    private javax.swing.JTextArea displayNodesField;
    private javax.swing.JLabel durationErrorLbl;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton helpBtn;
    private javax.swing.JTextArea infoTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listIndividualNodes;
    private javax.swing.JButton listPathsBtn;
    private javax.swing.JTextField nodeDependenciesTxt;
    private javax.swing.JLabel nodeDependencieslbl;
    private javax.swing.JTextField nodeDurationTxt;
    private javax.swing.JLabel nodeDurationlbl;
    private javax.swing.JTextField nodeNameTxt;
    private javax.swing.JLabel nodeNamelbl;
    private javax.swing.JLabel repoRequired;
    private javax.swing.JButton report;
    private javax.swing.JLabel reportTitle;
    private javax.swing.JTextField reportTitleTxt;
    private javax.swing.JLabel requiredLbl;
    // End of variables declaration//GEN-END:variables
}
